include theos/makefiles/common.mk

BUNDLE_NAME = DeliveryReportSettings
DeliveryReportSettings_FILES = DeliveryReportSettings.mm
DeliveryReportSettings_INSTALL_PATH = /System/Library/PreferenceBundles
DeliveryReportSettings_FRAMEWORKS = UIKit
DeliveryReportSettings_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS_MAKE_PATH)/bundle.mk

