#!/bin/sh
declare -a cydia
cydia=($CYDIA)

SMS_DATABASE="/var/mobile/Library/SMS/sms.db"

# alter SMS database to insert a few column used to store our info
# so we can link a report to a message and display its details
#
# smsc_ref: the transient ref returned by the SMSC. 
# s_date: the SMSC date the sms was submited
# r_date: the SMSC date the sms was delivered
# delivery_status : the status code found in the report
echo "Modify database structure"
sqlite3 $SMS_DATABASE '.schema message' | grep -q smsc_ref
if [ $? -eq 1 ]; then
	sqlite3 $SMS_DATABASE 'ALTER TABLE message ADD COLUMN smsc_ref INTEGER DEFAULT NULL'
fi
sqlite3 $SMS_DATABASE '.schema message' | grep -q s_date
if [ $? -eq 1 ]; then
	sqlite3 $SMS_DATABASE 'ALTER TABLE message ADD COLUMN s_date INTEGER DEFAULT NULL'
fi
# although dr_date is from previous version we still need it as queries refer to it
sqlite3 $SMS_DATABASE '.schema message' | grep -q dr_date
if [ $? -eq 1 ]; then
	sqlite3 $SMS_DATABASE 'ALTER TABLE message ADD COLUMN dr_date INTEGER DEFAULT NULL'
fi
sqlite3 $SMS_DATABASE '.schema message' | grep -w -q r_date
if [ $? -eq 1 ]; then
	sqlite3 $SMS_DATABASE 'ALTER TABLE message ADD COLUMN r_date INTEGER DEFAULT NULL'
fi
sqlite3 $SMS_DATABASE '.schema message' | grep -q delivery_status
if [ $? -eq 1 ]; then
	sqlite3 $SMS_DATABASE 'ALTER TABLE message ADD COLUMN delivery_status INTEGER DEFAULT NULL'
fi

echo "Modify Settings's Message pane to add our settings"
MESSAGES_PLIST=/System/Library/PrivateFrameworks/Conference.framework/Messages.plist
ENTRY=16

plutil -key items -key $ENTRY -dict $MESSAGES_PLIST > /dev/null
plutil -key items -key $ENTRY -key cell -string PSGroupCell $MESSAGES_PLIST > /dev/null

plutil -key items -key $((ENTRY+1)) -dict $MESSAGES_PLIST > /dev/null
plutil -key items -key $((ENTRY+1)) -key bundle -string DeliveryReportSettings $MESSAGES_PLIST > /dev/null
plutil -key items -key $((ENTRY+1)) -key cell -string PSLinkCell $MESSAGES_PLIST > /dev/null
#plutil -key items -key $((ENTRY+1)) -key hasIcon -yes $MESSAGES_PLIST 2> /dev/null
plutil -key items -key $((ENTRY+1)) -key isController -yes $MESSAGES_PLIST > /dev/null
plutil -key items -key $((ENTRY+1)) -key label -string DELIVERY_RECEIPTS $MESSAGES_PLIST > /dev/null

echo "inject our magic potion into CommCenter"
PLIST=/System/Library/LaunchDaemons/com.apple.CommCenterClassic.plist
LIBRARY=$(plutil -key EnvironmentVariables -key DYLD_INSERT_LIBRARIES $PLIST 2> /dev/null)
if [ -z "$LIBRARY" ]; then
	plutil -key EnvironmentVariables -dict $PLIST > /dev/null
	plutil -key EnvironmentVariables -key DYLD_INSERT_LIBRARIES \
		   -setValue /usr/local/lib/libidcc.dylib \
	 	$PLIST > /dev/null
else
	plutil -key EnvironmentVariables -dict $PLIST > /dev/null
	plutil -key EnvironmentVariables -key DYLD_INSERT_LIBRARIES \
		   -setValue "${LIBRARY}:/usr/local/lib/libidcc.dylib" \
	 	$PLIST > /dev/null
fi

echo "Restart CommCenter"
launchctl unload /System/Library/LaunchDaemons/com.apple.CommCenterClassic.plist
launchctl load /System/Library/LaunchDaemons/com.apple.CommCenterClassic.plist

echo "set a default configuration if there is none"
if [ ! -e /var/mobile/Library/Preferences/com.guilleme.deliveryreports.plist ]; then
   mv '/Library/Application Support/ID.bundle/com.guilleme.deliveryreports.plist' \
		/var/mobile/Library/Preferences/com.guilleme.deliveryreports.plist
fi

if [[ ${CYDIA+@} ]]; then
eval "echo 'finish:restart' >& ${cydia[0]}"
fi
