#!/bin/sh
declare -a cydia
cydia=($CYDIA)

SMS_DATABASE="/var/mobile/Library/SMS/sms.db"
VERSION=%VERSION%

# alter SMS database to insert a few column used to store our info
# so we can link a report to a message and display its details
#
# smsc_ref: the transient ref returned by the SMSC. 
# s_date: the SMSC date the sms was submited
# r_date: the SMSC date the sms was delivered
# delivery_status : the status code found in the report
echo "Modify database structure"
sqlite3 $SMS_DATABASE '.schema message' | grep -q smsc_ref
if [ $? -eq 1 ]; then
	sqlite3 $SMS_DATABASE 'ALTER TABLE message ADD COLUMN smsc_ref INTEGER DEFAULT NULL'
fi
sqlite3 $SMS_DATABASE '.schema message' | grep -q s_date
if [ $? -eq 1 ]; then
	sqlite3 $SMS_DATABASE 'ALTER TABLE message ADD COLUMN s_date INTEGER DEFAULT NULL'
fi
# although dr_date is from previous version we still need it as queries refer to it
sqlite3 $SMS_DATABASE '.schema message' | grep -q dr_date
if [ $? -eq 1 ]; then
	sqlite3 $SMS_DATABASE 'ALTER TABLE message ADD COLUMN dr_date INTEGER DEFAULT NULL'
fi
sqlite3 $SMS_DATABASE '.schema message' | grep -w -q r_date
if [ $? -eq 1 ]; then
	sqlite3 $SMS_DATABASE 'ALTER TABLE message ADD COLUMN r_date INTEGER DEFAULT NULL'
fi
sqlite3 $SMS_DATABASE '.schema message' | grep -q delivery_status
if [ $? -eq 1 ]; then
	sqlite3 $SMS_DATABASE 'ALTER TABLE message ADD COLUMN delivery_status INTEGER DEFAULT NULL'
fi

echo "Modify Settings's Message pane to add our settings"
MESSAGES_PLIST=/System/Library/PrivateFrameworks/Conference.framework/Messages.plist
# save the plist for an easier restore (if nobody touched it....)
cp $MESSAGES_PLIST ${MESSAGES_PLIST}_ID
ENTRY=16

plutil -key items -key $ENTRY -dict $MESSAGES_PLIST > /dev/null
plutil -key items -key $ENTRY -key cell -string PSGroupCell $MESSAGES_PLIST > /dev/null

plutil -key items -key $((ENTRY+1)) -dict $MESSAGES_PLIST > /dev/null
plutil -key items -key $((ENTRY+1)) -key bundle -string DeliveryReportSettings $MESSAGES_PLIST > /dev/null
plutil -key items -key $((ENTRY+1)) -key cell -string PSLinkCell $MESSAGES_PLIST > /dev/null
plutil -key items -key $((ENTRY+1)) -key isController -yes $MESSAGES_PLIST > /dev/null
plutil -key items -key $((ENTRY+1)) -key label -string DELIVERY_RECEIPTS $MESSAGES_PLIST > /dev/null

# change the user of CommCenter back to root (this is pretty unsafe)
PLIST=/System/Library/LaunchDaemons/com.apple.CommCenterClassic.plist
USER=$(plutil -key UserName $PLIST 2> /dev/null)
if [ -n "$USER" ]; then
	plutil -key _UserName -value $USER  $PLIST > /dev/null
	plutil -key UserName -remove  $PLIST > /dev/null
fi

echo update statistics
/usr/bin/libidtool $VERSION

echo "Hook and reload CommCenter"
chown root:wheel /System/Library/LaunchDaemons/com.guilleme.CommCenterRestart.plist
launchctl unload /System/Library/LaunchDaemons/com.guilleme.CommCenterRestart.plist
launchctl load /System/Library/LaunchDaemons/com.guilleme.CommCenterRestart.plist

#launchctl unload /System/Library/LaunchDaemons/com.apple.CommCenterClassic.plist
#launchctl load /System/Library/LaunchDaemons/com.apple.CommCenterClassic.plist

echo "set a default configuration if there is none"
if [ ! -e /var/mobile/Library/Preferences/com.guilleme.deliveryreports.plist ]; then
   mv '/Library/Application Support/ID.bundle/com.guilleme.deliveryreports.plist' \
		/var/mobile/Library/Preferences/com.guilleme.deliveryreports.plist
fi

if [[ ${CYDIA+@} ]]; then
eval "echo 'finish:restart' >& ${cydia[0]}"
fi
