#!/bin/sh
declare -a cydia
cydia=($CYDIA)

SMS_DATABASE="/var/mobile/Library/SMS/sms.db"

# alter SMS database to insert a few column used to store our info
# so we can link a report to a message and display its details
#
# smsc_ref: the transient ref returned by the SMSC. 
# s_date: the SMSC date the sms was submited
# r_date: the SMSC date the sms was delivered
# delivery_status : the status code found in the report
sqlite3 $SMS_DATABASE '.schema message' | grep -q smsc_ref
if [ $? -eq 1 ]; then
	sqlite3 $SMS_DATABASE 'ALTER TABLE message ADD COLUMN smsc_ref INTEGER DEFAULT NULL'
fi
sqlite3 $SMS_DATABASE '.schema message' | grep -q s_date
if [ $? -eq 1 ]; then
	sqlite3 $SMS_DATABASE 'ALTER TABLE message ADD COLUMN s_date INTEGER DEFAULT NULL'
fi
sqlite3 $SMS_DATABASE '.schema message' | grep -v dr_date | grep -q r_date
if [ $? -eq 1 ]; then
	sqlite3 $SMS_DATABASE 'ALTER TABLE message ADD COLUMN r_date INTEGER DEFAULT NULL'
fi
sqlite3 $SMS_DATABASE '.schema message' | grep -q delivery_status
if [ $? -eq 1 ]; then
	sqlite3 $SMS_DATABASE 'ALTER TABLE message ADD COLUMN delivery_status INTEGER DEFAULT NULL'
fi

PLIST=/System/Library/LaunchDaemons/com.apple.CommCenterClassic.plist
LIBRARY=$(plutil -key EnvironmentVariables -key DYLD_INSERT_LIBRARIES $PLIST 2> /dev/null)
if [ -z "$LIBRARY" ]; then
	plutil -key EnvironmentVariables -dict $PLIST;
	plutil -key EnvironmentVariables -key DYLD_INSERT_LIBRARIES \
		   -setValue /usr/local/lib/libidcc.dylib \
	 	$PLIST;
else
	plutil -key EnvironmentVariables -dict $PLIST;
	plutil -key EnvironmentVariables -key DYLD_INSERT_LIBRARIES \
		   -setValue "${LIBRARY}:/usr/local/lib/libidcc.dylib" \
	 	$PLIST;
fi
echo CommCenter inserted libraries
plutil -key EnvironmentVariables $PLIST

launchctl unload /System/Library/LaunchDaemons/com.apple.CommCenterClassic.plist
launchctl load /System/Library/LaunchDaemons/com.apple.CommCenterClassic.plist

mv /var/stash/Applications/Preferences.app/{,ID2}Settings.plist
mv /var/stash/Applications/Preferences.app/{ID,}Settings.plist

if [[ ${CYDIA+@} ]]; then
eval "echo 'finish:restart' >& ${cydia[0]}"
fi
