#!/bin/sh
declare -a cydia
cydia=($CYDIA)

PLIST=/System/Library/LaunchDaemons/com.apple.CommCenterClassic.plist
LIBRARY=$(plutil -key EnvironmentVariables -key DYLD_INSERT_LIBRARIES $PLIST 2> /dev/null)
if [ -n "$LIBRARY" ]; then
	LIBRARY=$(echo $LIBRARY | sed -e s^/usr/local/lib/libidcc.dylib^^ -e s/^:// -e s/::// -e 's/:$//')
	if [ -z "$LIBRARY" ]; then
		plutil -key EnvironmentVariables -remove $PLIST > /dev/null

	else
		plutil -key EnvironmentVariables -key DYLD_INSERT_LIBRARIES -setValue "$LIBRARY" $PLIST > /dev/null
	fi
fi

cd /Applications/Preferences.app/
MESSAGES_PLIST=/System/Library/PrivateFrameworks/Conference.framework/Messages.plist
ENTRY=16

echo "Remove our settings"
plutil -key items -key $ENTRY -key cell -remove $MESSAGES_PLIST > /dev/null
plutil -key items -key $((ENTRY+1)) -key bundle -remove $MESSAGES_PLIST > /dev/null
plutil -key items -key $((ENTRY+1)) -key cell -remove $MESSAGES_PLIST > /dev/null
#plutil -key items -key $((ENTRY+1)) -key hasIcon -remove $MESSAGES_PLIST > /dev/null
plutil -key items -key $((ENTRY+1)) -key isController -remove $MESSAGES_PLIST > /dev/null
plutil -key items -key $((ENTRY+1)) -key label -remove $MESSAGES_PLIST > /dev/null

echo "Restart CommCenter"
launchctl unload /System/Library/LaunchDaemons/com.apple.CommCenterClassic.plist
launchctl load /System/Library/LaunchDaemons/com.apple.CommCenterClassic.plist

if [[ ${CYDIA+@} ]]; then
eval "echo 'finish:restart' >& ${cydia[0]}"
fi
