#!/bin/sh
declare -a cydia
cydia=($CYDIA)

for lang in /Applications/Preferences.app/*.lproj; do
   plutil -key "Delivery reports" -remove $lang/Settings~iphone.strings  > /dev/null
done

plutil -key EnvironmentVariables -remove /System/Library/LaunchDaemons/com.apple.CommCenterClassic.plist

cd /Applications/Preferences.app/
MESSAGES_PLIST=/System/Library/PrivateFrameworks/Conference.framework/Messages.plist
ENTRY=16

plutil -key items -key $ENTRY -key cell -remove $MESSAGES_PLIST > /dev/null
plutil -key items -key $((ENTRY+1)) -key bundle -remove $MESSAGES_PLIST > /dev/null
plutil -key items -key $((ENTRY+1)) -key cell -remove $MESSAGES_PLIST > /dev/null
#plutil -key items -key $((ENTRY+1)) -key hasIcon -remove $MESSAGES_PLIST > /dev/null
plutil -key items -key $((ENTRY+1)) -key isController -remove $MESSAGES_PLIST > /dev/null
plutil -key items -key $((ENTRY+1)) -key label -remove $MESSAGES_PLIST > /dev/null

launchctl unload /System/Library/LaunchDaemons/com.apple.CommCenterClassic.plist
launchctl load /System/Library/LaunchDaemons/com.apple.CommCenterClassic.plist

if [[ ${CYDIA+@} ]]; then
eval "echo 'finish:restart' >& ${cydia[0]}"
#else
#launchctl stop com.apple.SpringBoard
#launchctl start com.apple.SpringBoard
fi
